apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
    app: rw
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "5000"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:5000
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /opt/query/storage.json
          - name: BUCKET_FREEZE
            value: query-freeze
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: GCLOUD_STORAGE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: GCLOUD_BACKUPS_CREDENTIALS

        ports:
          - containerPort: 5000

      restartPolicy: Always
